### ISSUE TITLE
frame resize bug!

### ISSUE THREAD

**Issue by MarcusNerva** [hobincar/pytorch-video-feature-extractor#10]
Greetings!

In function cv2.resize(img, target_size), you should let target_size=(target_width, target_height), rather than (target_height, target_width). I check the docs of opencv and find this bug.

https://github.com/hobincar/pytorch-video-feature-extractor/blob/1128768ae7c113286b664340c45c6e85a8560027/commons.py#L13

**Comment by hobincar** [comment]
Hi!
Thank you for reporting this bug. I was always using squared images, so I didn't notice the bug.
