### ISSUE TITLE
How to download the MSVD dataset?

### ISSUE THREAD

**Issue by maoao686868** [hobincar/pytorch-video-feature-extractor#6]
@hobincar Hi, when you say you prepared dataset, how to prepare the datasets?  I mean how to download the MSVD dataset, is there any link?

**Comment by hobincar** [comment]
Hi. Yes, you can download it from [here](https://www.microsoft.com/en-us/download/details.aspx?id=52422&from=https%3A%2F%2Fresearch.microsoft.com%2Fen-us%2Fdownloads%2F38cf15fd-b8df-477e-a4e4-a4680caa75af%2F).

**Comment by maoao686868** [comment]
@hobincar  Thank you very much, it is very useful for my research.
