### ISSUE TITLE
where is module abc

### ISSUE THREAD

**Issue by maoao686868** [hobincar/pytorch-video-feature-extractor#7]
@hobincar  Hi , I am sorry to disturb you again. This week I want to use inceptionv4 net to extract features from the datasets. When I run this project, I find the "from abc import ABC" this sentence from the config.py in the project, but I cannot find where the abc module defination is.  Please help me.

**Comment by hobincar** [comment]
Hi @maoao686868, The module abc is the built-in module in python language. The [docs](https://docs.python.org/3.6/library/abc.html) is saying that it is added in version 3.4, and I guess you are using an older version of python.

**Comment by maoao686868** [comment]
@hobincar I am sorry. Yes, I forget to change the python version since these codes are based on python 3.6.8 virtual environment, and the code for "Reconstruction for video captioning" is based on the python2.7.12 virtual environment.
